// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chord.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Lookup struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lookup) Reset()         { *m = Lookup{} }
func (m *Lookup) String() string { return proto.CompactTextString(m) }
func (*Lookup) ProtoMessage()    {}
func (*Lookup) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{0}
}

func (m *Lookup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lookup.Unmarshal(m, b)
}
func (m *Lookup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lookup.Marshal(b, m, deterministic)
}
func (m *Lookup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lookup.Merge(m, src)
}
func (m *Lookup) XXX_Size() int {
	return xxx_messageInfo_Lookup.Size(m)
}
func (m *Lookup) XXX_DiscardUnknown() {
	xxx_messageInfo_Lookup.DiscardUnknown(m)
}

var xxx_messageInfo_Lookup proto.InternalMessageInfo

func (m *Lookup) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type MerkleNode struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Left                 []byte   `protobuf:"bytes,2,opt,name=Left,proto3" json:"Left,omitempty"`
	Right                []byte   `protobuf:"bytes,3,opt,name=Right,proto3" json:"Right,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerkleNode) Reset()         { *m = MerkleNode{} }
func (m *MerkleNode) String() string { return proto.CompactTextString(m) }
func (*MerkleNode) ProtoMessage()    {}
func (*MerkleNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{1}
}

func (m *MerkleNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerkleNode.Unmarshal(m, b)
}
func (m *MerkleNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerkleNode.Marshal(b, m, deterministic)
}
func (m *MerkleNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerkleNode.Merge(m, src)
}
func (m *MerkleNode) XXX_Size() int {
	return xxx_messageInfo_MerkleNode.Size(m)
}
func (m *MerkleNode) XXX_DiscardUnknown() {
	xxx_messageInfo_MerkleNode.DiscardUnknown(m)
}

var xxx_messageInfo_MerkleNode proto.InternalMessageInfo

func (m *MerkleNode) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *MerkleNode) GetLeft() []byte {
	if m != nil {
		return m.Left
	}
	return nil
}

func (m *MerkleNode) GetRight() []byte {
	if m != nil {
		return m.Right
	}
	return nil
}

type MerkleTree struct {
	Nodes                []*MerkleNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	RootHash             []byte        `protobuf:"bytes,2,opt,name=rootHash,proto3" json:"rootHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MerkleTree) Reset()         { *m = MerkleTree{} }
func (m *MerkleTree) String() string { return proto.CompactTextString(m) }
func (*MerkleTree) ProtoMessage()    {}
func (*MerkleTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{2}
}

func (m *MerkleTree) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerkleTree.Unmarshal(m, b)
}
func (m *MerkleTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerkleTree.Marshal(b, m, deterministic)
}
func (m *MerkleTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerkleTree.Merge(m, src)
}
func (m *MerkleTree) XXX_Size() int {
	return xxx_messageInfo_MerkleTree.Size(m)
}
func (m *MerkleTree) XXX_DiscardUnknown() {
	xxx_messageInfo_MerkleTree.DiscardUnknown(m)
}

var xxx_messageInfo_MerkleTree proto.InternalMessageInfo

func (m *MerkleTree) GetNodes() []*MerkleNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *MerkleTree) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

type ForwardSyncData struct {
	Data                 []byte      `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	PredecessorListHash  []byte      `protobuf:"bytes,2,opt,name=predecessorListHash,proto3" json:"predecessorListHash,omitempty"`
	MerkleTree           *MerkleTree `protobuf:"bytes,3,opt,name=merkleTree,proto3" json:"merkleTree,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ForwardSyncData) Reset()         { *m = ForwardSyncData{} }
func (m *ForwardSyncData) String() string { return proto.CompactTextString(m) }
func (*ForwardSyncData) ProtoMessage()    {}
func (*ForwardSyncData) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{3}
}

func (m *ForwardSyncData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardSyncData.Unmarshal(m, b)
}
func (m *ForwardSyncData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardSyncData.Marshal(b, m, deterministic)
}
func (m *ForwardSyncData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardSyncData.Merge(m, src)
}
func (m *ForwardSyncData) XXX_Size() int {
	return xxx_messageInfo_ForwardSyncData.Size(m)
}
func (m *ForwardSyncData) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardSyncData.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardSyncData proto.InternalMessageInfo

func (m *ForwardSyncData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ForwardSyncData) GetPredecessorListHash() []byte {
	if m != nil {
		return m.PredecessorListHash
	}
	return nil
}

func (m *ForwardSyncData) GetMerkleTree() *MerkleTree {
	if m != nil {
		return m.MerkleTree
	}
	return nil
}

type Content struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{4}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Node struct {
	IP                   string   `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{5}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *Node) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type StablizerData struct {
	Predecessor          *Node    `protobuf:"bytes,1,opt,name=Predecessor,proto3" json:"Predecessor,omitempty"`
	SuccessorList        []*Node  `protobuf:"bytes,2,rep,name=SuccessorList,proto3" json:"SuccessorList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StablizerData) Reset()         { *m = StablizerData{} }
func (m *StablizerData) String() string { return proto.CompactTextString(m) }
func (*StablizerData) ProtoMessage()    {}
func (*StablizerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{6}
}

func (m *StablizerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StablizerData.Unmarshal(m, b)
}
func (m *StablizerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StablizerData.Marshal(b, m, deterministic)
}
func (m *StablizerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StablizerData.Merge(m, src)
}
func (m *StablizerData) XXX_Size() int {
	return xxx_messageInfo_StablizerData.Size(m)
}
func (m *StablizerData) XXX_DiscardUnknown() {
	xxx_messageInfo_StablizerData.DiscardUnknown(m)
}

var xxx_messageInfo_StablizerData proto.InternalMessageInfo

func (m *StablizerData) GetPredecessor() *Node {
	if m != nil {
		return m.Predecessor
	}
	return nil
}

func (m *StablizerData) GetSuccessorList() []*Node {
	if m != nil {
		return m.SuccessorList
	}
	return nil
}

type Nodes struct {
	Nodes                []*Node  `protobuf:"bytes,1,rep,name=Nodes,proto3" json:"Nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nodes) Reset()         { *m = Nodes{} }
func (m *Nodes) String() string { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()    {}
func (*Nodes) Descriptor() ([]byte, []int) {
	return fileDescriptor_541dae51990542ec, []int{7}
}

func (m *Nodes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nodes.Unmarshal(m, b)
}
func (m *Nodes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nodes.Marshal(b, m, deterministic)
}
func (m *Nodes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nodes.Merge(m, src)
}
func (m *Nodes) XXX_Size() int {
	return xxx_messageInfo_Nodes.Size(m)
}
func (m *Nodes) XXX_DiscardUnknown() {
	xxx_messageInfo_Nodes.DiscardUnknown(m)
}

var xxx_messageInfo_Nodes proto.InternalMessageInfo

func (m *Nodes) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*Lookup)(nil), "grpc.Lookup")
	proto.RegisterType((*MerkleNode)(nil), "grpc.MerkleNode")
	proto.RegisterType((*MerkleTree)(nil), "grpc.MerkleTree")
	proto.RegisterType((*ForwardSyncData)(nil), "grpc.ForwardSyncData")
	proto.RegisterType((*Content)(nil), "grpc.Content")
	proto.RegisterType((*Node)(nil), "grpc.Node")
	proto.RegisterType((*StablizerData)(nil), "grpc.StablizerData")
	proto.RegisterType((*Nodes)(nil), "grpc.Nodes")
}

func init() {
	proto.RegisterFile("chord.proto", fileDescriptor_541dae51990542ec)
}

var fileDescriptor_541dae51990542ec = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xcd, 0x47, 0x1d, 0x60, 0x9c, 0x94, 0x68, 0x0b, 0xc8, 0x32, 0x02, 0x45, 0x7b, 0x40, 0xa5,
	0x20, 0x27, 0x0a, 0xe5, 0xc0, 0x81, 0x0b, 0x85, 0x96, 0x42, 0x88, 0x2c, 0x07, 0x71, 0x77, 0xec,
	0x4d, 0x62, 0xd5, 0xf5, 0x58, 0xeb, 0x8d, 0xaa, 0xf0, 0x0f, 0xf8, 0x9b, 0xfc, 0x12, 0xb4, 0xbb,
	0x49, 0xbc, 0x36, 0x41, 0xdc, 0xc6, 0xf3, 0xde, 0xcc, 0xbc, 0x37, 0x9e, 0x05, 0x3b, 0x5a, 0x21,
	0x8f, 0xbd, 0x9c, 0xa3, 0x40, 0x72, 0xb4, 0xe4, 0x79, 0xe4, 0x3e, 0x5d, 0x22, 0x2e, 0x53, 0x36,
	0x54, 0xb9, 0xf9, 0x7a, 0x31, 0x64, 0xb7, 0xb9, 0xd8, 0x68, 0x8a, 0xfb, 0xbc, 0x0e, 0xde, 0xf1,
	0x30, 0xcf, 0x19, 0x2f, 0x34, 0x4e, 0x5d, 0xe8, 0x4c, 0x10, 0x6f, 0xd6, 0x39, 0xe9, 0x43, 0xfb,
	0x2b, 0xdb, 0x38, 0xcd, 0x41, 0xf3, 0xb4, 0x1b, 0xc8, 0x90, 0x7e, 0x01, 0xf8, 0xc6, 0xf8, 0x4d,
	0xca, 0xa6, 0x18, 0x33, 0x42, 0xe0, 0xe8, 0x73, 0x58, 0xac, 0xb6, 0x04, 0x15, 0xcb, 0xdc, 0x84,
	0x2d, 0x84, 0xd3, 0xd2, 0x39, 0x19, 0x93, 0x47, 0x60, 0x05, 0xc9, 0x72, 0x25, 0x9c, 0xb6, 0x4a,
	0xea, 0x0f, 0xea, 0xef, 0x7a, 0x7d, 0xe7, 0x8c, 0x91, 0x17, 0x60, 0x65, 0x18, 0xb3, 0xc2, 0x69,
	0x0e, 0xda, 0xa7, 0xf6, 0xb8, 0xef, 0x49, 0x23, 0x5e, 0x39, 0x2c, 0xd0, 0x30, 0x71, 0xe1, 0x3e,
	0x47, 0x14, 0x6a, 0xae, 0x9e, 0xb1, 0xff, 0xa6, 0xbf, 0x9a, 0xf0, 0xf0, 0x12, 0xf9, 0x5d, 0xc8,
	0xe3, 0xd9, 0x26, 0x8b, 0x3e, 0x86, 0x22, 0x94, 0x7a, 0xe2, 0x50, 0x84, 0x3b, 0x8d, 0x32, 0x26,
	0x23, 0x38, 0xc9, 0x39, 0x8b, 0x59, 0xc4, 0x8a, 0x02, 0xf9, 0x24, 0x29, 0xcc, 0x76, 0x87, 0x20,
	0x32, 0x02, 0xb8, 0xdd, 0x6b, 0x55, 0x36, 0x6a, 0x12, 0x65, 0x3e, 0x30, 0x38, 0xf4, 0x19, 0xdc,
	0xbb, 0xc0, 0x4c, 0xb0, 0x4c, 0x1c, 0x92, 0x40, 0xcf, 0xe0, 0x48, 0xad, 0xf0, 0x18, 0x5a, 0xd7,
	0xbe, 0x42, 0x1e, 0x04, 0xad, 0x6b, 0x5f, 0x72, 0x7d, 0xe4, 0x7a, 0x7d, 0x56, 0xa0, 0x62, 0x8a,
	0xd0, 0x9b, 0x89, 0x70, 0x9e, 0x26, 0x3f, 0x19, 0x57, 0x9e, 0x5e, 0x83, 0xed, 0x97, 0x22, 0x55,
	0xb5, 0x3d, 0x06, 0x2d, 0x47, 0xed, 0xca, 0x84, 0xc9, 0x08, 0x7a, 0xb3, 0x75, 0x54, 0x1a, 0x72,
	0x5a, 0x6a, 0xc3, 0x26, 0xbf, 0x4a, 0xa0, 0x2f, 0xc1, 0x9a, 0xaa, 0x65, 0x0f, 0xb6, 0xc1, 0xf6,
	0xa7, 0x98, 0x25, 0x1a, 0x18, 0xff, 0x6e, 0x83, 0x75, 0x21, 0xef, 0x8f, 0x9c, 0x43, 0xf7, 0x8a,
	0x89, 0x7d, 0x23, 0xf2, 0xc4, 0xd3, 0x77, 0xe6, 0xed, 0xee, 0xcc, 0xfb, 0x24, 0x8f, 0xd0, 0x35,
	0x9a, 0xd0, 0x06, 0x79, 0x05, 0xbd, 0xcb, 0x24, 0x8b, 0xcb, 0xb2, 0xae, 0x86, 0xf5, 0x05, 0xd6,
	0xc8, 0x67, 0x70, 0x7c, 0xc5, 0x84, 0xe9, 0xcd, 0xc0, 0x6b, 0xdc, 0x31, 0x74, 0xa6, 0x28, 0x92,
	0xc5, 0xa6, 0xc2, 0x71, 0xff, 0x12, 0xf5, 0x01, 0x31, 0xfd, 0x11, 0xa6, 0x6b, 0x59, 0xf3, 0x0e,
	0xfa, 0xa6, 0x05, 0xb9, 0x8b, 0x7f, 0xda, 0xb0, 0xcb, 0xae, 0x05, 0x6d, 0x90, 0xb7, 0xba, 0xb4,
	0xf2, 0x9b, 0xcc, 0xc1, 0x27, 0x3a, 0xae, 0x10, 0x68, 0x83, 0x0c, 0x81, 0x54, 0x1d, 0xa9, 0x99,
	0x66, 0x61, 0x6d, 0xce, 0x39, 0x58, 0x33, 0x81, 0x9c, 0x91, 0x9e, 0xce, 0x6f, 0x6f, 0xec, 0x3f,
	0xc6, 0xde, 0x83, 0x6d, 0xbc, 0x0b, 0xf2, 0x58, 0xd7, 0xd6, 0x9e, 0x8a, 0x7b, 0x38, 0x4d, 0x1b,
	0xf3, 0x8e, 0x6a, 0xfa, 0xe6, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xf0, 0x53, 0x32, 0x6a,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChordClient is the client API for Chord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChordClient interface {
	GetSuccessor(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Node, error)
	FindSuccessor(ctx context.Context, in *Lookup, opts ...grpc.CallOption) (*Node, error)
	GetPredecessor(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Node, error)
	Notify(ctx context.Context, in *Node, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	GetSuccessorList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Nodes, error)
	GetStablizerData(ctx context.Context, in *Node, opts ...grpc.CallOption) (*StablizerData, error)
	GetPredecessorList(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Nodes, error)
	Store(ctx context.Context, in *Content, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
	ForwardSync(ctx context.Context, in *ForwardSyncData, opts ...grpc.CallOption) (*ForwardSyncData, error)
}

type chordClient struct {
	cc grpc.ClientConnInterface
}

func NewChordClient(cc grpc.ClientConnInterface) ChordClient {
	return &chordClient{cc}
}

func (c *chordClient) GetSuccessor(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/grpc.Chord/GetSuccessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) FindSuccessor(ctx context.Context, in *Lookup, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/grpc.Chord/FindSuccessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) GetPredecessor(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Node, error) {
	out := new(Node)
	err := c.cc.Invoke(ctx, "/grpc.Chord/GetPredecessor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) Notify(ctx context.Context, in *Node, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/grpc.Chord/Notify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) GetSuccessorList(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Nodes, error) {
	out := new(Nodes)
	err := c.cc.Invoke(ctx, "/grpc.Chord/GetSuccessorList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) GetStablizerData(ctx context.Context, in *Node, opts ...grpc.CallOption) (*StablizerData, error) {
	out := new(StablizerData)
	err := c.cc.Invoke(ctx, "/grpc.Chord/GetStablizerData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) GetPredecessorList(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Nodes, error) {
	out := new(Nodes)
	err := c.cc.Invoke(ctx, "/grpc.Chord/GetPredecessorList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) Store(ctx context.Context, in *Content, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/grpc.Chord/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chordClient) ForwardSync(ctx context.Context, in *ForwardSyncData, opts ...grpc.CallOption) (*ForwardSyncData, error) {
	out := new(ForwardSyncData)
	err := c.cc.Invoke(ctx, "/grpc.Chord/ForwardSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChordServer is the server API for Chord service.
type ChordServer interface {
	GetSuccessor(context.Context, *empty.Empty) (*Node, error)
	FindSuccessor(context.Context, *Lookup) (*Node, error)
	GetPredecessor(context.Context, *Node) (*Node, error)
	Notify(context.Context, *Node) (*wrappers.BoolValue, error)
	GetSuccessorList(context.Context, *empty.Empty) (*Nodes, error)
	GetStablizerData(context.Context, *Node) (*StablizerData, error)
	GetPredecessorList(context.Context, *Node) (*Nodes, error)
	Store(context.Context, *Content) (*wrappers.BoolValue, error)
	ForwardSync(context.Context, *ForwardSyncData) (*ForwardSyncData, error)
}

// UnimplementedChordServer can be embedded to have forward compatible implementations.
type UnimplementedChordServer struct {
}

func (*UnimplementedChordServer) GetSuccessor(ctx context.Context, req *empty.Empty) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuccessor not implemented")
}
func (*UnimplementedChordServer) FindSuccessor(ctx context.Context, req *Lookup) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindSuccessor not implemented")
}
func (*UnimplementedChordServer) GetPredecessor(ctx context.Context, req *Node) (*Node, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPredecessor not implemented")
}
func (*UnimplementedChordServer) Notify(ctx context.Context, req *Node) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (*UnimplementedChordServer) GetSuccessorList(ctx context.Context, req *empty.Empty) (*Nodes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuccessorList not implemented")
}
func (*UnimplementedChordServer) GetStablizerData(ctx context.Context, req *Node) (*StablizerData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStablizerData not implemented")
}
func (*UnimplementedChordServer) GetPredecessorList(ctx context.Context, req *Node) (*Nodes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPredecessorList not implemented")
}
func (*UnimplementedChordServer) Store(ctx context.Context, req *Content) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (*UnimplementedChordServer) ForwardSync(ctx context.Context, req *ForwardSyncData) (*ForwardSyncData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardSync not implemented")
}

func RegisterChordServer(s *grpc.Server, srv ChordServer) {
	s.RegisterService(&_Chord_serviceDesc, srv)
}

func _Chord_GetSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).GetSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Chord/GetSuccessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).GetSuccessor(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_FindSuccessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Lookup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).FindSuccessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Chord/FindSuccessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).FindSuccessor(ctx, req.(*Lookup))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_GetPredecessor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).GetPredecessor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Chord/GetPredecessor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).GetPredecessor(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Chord/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).Notify(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_GetSuccessorList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).GetSuccessorList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Chord/GetSuccessorList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).GetSuccessorList(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_GetStablizerData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).GetStablizerData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Chord/GetStablizerData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).GetStablizerData(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_GetPredecessorList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).GetPredecessorList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Chord/GetPredecessorList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).GetPredecessorList(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Content)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Chord/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).Store(ctx, req.(*Content))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chord_ForwardSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardSyncData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChordServer).ForwardSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Chord/ForwardSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChordServer).ForwardSync(ctx, req.(*ForwardSyncData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chord_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Chord",
	HandlerType: (*ChordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSuccessor",
			Handler:    _Chord_GetSuccessor_Handler,
		},
		{
			MethodName: "FindSuccessor",
			Handler:    _Chord_FindSuccessor_Handler,
		},
		{
			MethodName: "GetPredecessor",
			Handler:    _Chord_GetPredecessor_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _Chord_Notify_Handler,
		},
		{
			MethodName: "GetSuccessorList",
			Handler:    _Chord_GetSuccessorList_Handler,
		},
		{
			MethodName: "GetStablizerData",
			Handler:    _Chord_GetStablizerData_Handler,
		},
		{
			MethodName: "GetPredecessorList",
			Handler:    _Chord_GetPredecessorList_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _Chord_Store_Handler,
		},
		{
			MethodName: "ForwardSync",
			Handler:    _Chord_ForwardSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chord.proto",
}
